#!/bin/bash

echo "🏦 OBTENIENDO CUENTAS SANDBOX PAYPAL"
echo "===================================="
echo ""
echo "Para obtener las credenciales de las cuentas de prueba:"
echo ""
echo "1️⃣ Ve a: https://developer.paypal.com/"
echo "2️⃣ Inicia sesión con tu cuenta PayPal"
echo "3️⃣ Ve a 'Testing Tools' > 'Sandbox Accounts'"
echo "4️⃣ Verás cuentas como:"
echo "   📧 Comprador: sb-xxxxx@personal.example.com"
echo "   📧 Vendedor: sb-yyyyy@business.example.com"
echo "5️⃣ Click en cada cuenta para ver la password"
echo ""
echo "🔧 O crear nuevas cuentas:"
echo "   - Click 'Create Account'"
echo "   - Selecciona 'Personal' (para comprar)"
echo "   - Selecciona 'Business' (para vender)"
echo ""
echo "🎯 FLUJO DE PRUEBA:"
echo "   1. Crear orden → tu aplicación"
echo "   2. Pagar → cuenta Personal sandbox"  
echo "   3. Recibir → cuenta Business sandbox"
echo ""
echo "💡 URL de prueba actual:"
echo "   https://www.sandbox.paypal.com/checkoutnow?token=8B8490325V602130X"
echo ""
echo "ℹ️  Tip: Las cuentas sandbox solo funcionan en https://sandbox.paypal.com"